apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchers-deploy
  labels:
    app: watchers-app
  annotations:
spec:
  selector:
    matchLabels:
      app: watchers-app

  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: watchers-app
    spec:
      hostAliases:
      - ip: "159.89.250.255"
        hostnames:
        - "api.mapofzones.com"
      containers:

      - name: bitcanna-1
        image: registry.digitalocean.com/mapofzones/cosmos-watcher-bitcanna:b40f2d7b
        env:
          - name: chain_id
            value: "bitcanna-1"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "150Mi"
            cpu: "30m"
          limits:
            memory: "256Mi"
            cpu: "250m"

      # - name: cronostestnet-338
      #   image: registry.digitalocean.com/mapofzones/cosmos-watcher-cronos:95c7d6e5
      #   env:
      #     - name: chain_id
      #       value: "cronostestnet-338"
      #     - name: rabbitmq
      #       valueFrom:
      #         secretKeyRef:
      #           name: prodsecret
      #           key: watcher_rabbitmq
      #     - name: graphql
      #       valueFrom:
      #         secretKeyRef:
      #           name: prodsecret
      #           key: db_graphql
      #   imagePullPolicy: Always
      #   resources:
      #     requests:
      #       memory: "150Mi"
      #       cpu: "30m"
      #     limits:
      #       memory: "256Mi"
      #       cpu: "250m"
