apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchers-deploy
  labels:
    app: watchers-app
  annotations:
spec:
  selector:
    matchLabels:
      app: watchers-app

  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: watchers-app
    spec:
      hostAliases:
      - ip: "159.89.250.255"
        hostnames:
        - "api.mapofzones.com"
      containers:

      - name: cosmoshub-4
        image: registry.digitalocean.com/mapofzones/cosmos-watcher-cosmoshub:81ca5120
        env:
          - name: chain_id
            value: "cosmoshub-4"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "70Mi"
            cpu: "20m"
          limits:
            memory: "512Mi"
            cpu: "250m"

      - name: irishub-1
        image: registry.digitalocean.com/mapofzones/cosmos-watcher:0a158b32
        env:
          - name: chain_id
            value: "irishub-1"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "250m"

      - name: akashnet-2
        image: registry.digitalocean.com/mapofzones/cosmos-watcher:0a158b32
        env:
          - name: chain_id
            value: "akashnet-2"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "250m"

      - name: sentinelhub-2
        image: registry.digitalocean.com/mapofzones/cosmos-watcher:0a158b32
        env:
          - name: chain_id
            value: "sentinelhub-2"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "250m"

      - name: persistence-core-1
        image: registry.digitalocean.com/mapofzones/cosmos-watcher:0e8a510d
        env:
          - name: chain_id
            value: "core-1"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "250m"

      - name: osmosis-1
        image: registry.digitalocean.com/mapofzones/cosmos-watcher-osmosis:46c6ce1d
        env:
          - name: chain_id
            value: "osmosis-1"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"

      - name: crypto-org-chain-mainnet-1
        image: registry.digitalocean.com/mapofzones/cosmos-watcher:0e8a510d
        env:
          - name: chain_id
            value: "crypto-org-chain-mainnet-1"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "250m"

      - name: starname-iov-mainnet-ibc
        image: registry.digitalocean.com/mapofzones/cosmos-watcher-starname:8e279032
        env:
          - name: chain_id
            value: "iov-mainnet-ibc"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "150Mi"
            cpu: "30m"
          limits:
            memory: "256Mi"
            cpu: "250m"
