apiVersion: apps/v1
kind: Deployment
metadata:
  name: zone-height-checker-deploy
  labels:
    app: zone-height-checker-app
  annotations:
spec:
  selector:
    matchLabels:
      app: zone-height-checker-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: zone-height-checker-app
    spec:
      containers:
      - name: zone-height-checker
        image: registry.digitalocean.com/mapofzones/zone-height-checker:4cc3c744
        env:
          - name: SYNC_TYME
            value: "14400000" # in milliseconds -> 1000 * 60 * 60 * 4 = 3 600 000(1 hour) * 4 = 14 400 000 = 4 hour
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: zone-height-checker_DB_URL
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: zone-height-checker_DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: zone-height-checker_DB_PASS
          - name: CHAT_ID
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: zone-height-checker_CHAT_ID
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: zone-height-checker_TOKEN
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
