apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hasura
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: test.biteacon.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: hasura
          servicePort: 80
