apiVersion: argoproj.io/v1alpha1
metadata:
  name: dev-moz
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: dev
    repoURL: 'https://github.com/mapofzones/deploy.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
kind: Application