apiVersion: v1
kind: Secret
metadata:
  name: devsecret
  namespace: dev
type: Opaque
stringData:
  watcher_rabbitmq : amqp://<login>:<pass>@<ip>:<port>
  db_graphql : http://<ip>:<port>/v1/graphql
  processor_rabbitmq : amqp://<login>:<pass>@<ip>:<port>
  processor_db : postgres://<user>:<pass>@<ip>:<port>/<db>
  adaptor_DB_URL : jdbc:postgresql://<ip>:<port>/<db>
  adaptor_DB_USER : <db_user>
  adaptor_DB_PASS : <db_user_pass>
  hasura_db_url : postgres://<user>:<pass>@<ip>:<port>/<db>
  hasura_admin_secret : <pass>
  endpoint-checker_DB_URL : jdbc:postgresql://<ip>:<port>/<db>
  endpoint-checker_DB_USER : <db_user>
  endpoint-checker_DB_PASS : <db_user_pass>
# kubectl apply -f ./kubernetes/secrets/dev-secret.yaml