apiVersion: v1
kind: Secret
metadata:
  name: devsecret
  namespace: dev
type: Opaque
stringData:
  watcher_rabbitmq : amqp://<login>:<pass>@<ip>:<port>
  db_graphql : http://<ip>:<port>/v1/graphql
# kubectl apply -f ./kubernetes/secrets/dev-secret.yaml