apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  labels:
    app: example-app
  annotations:
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: registry.digitalocean.com/mapofzones/cosmos-watcher@sha256:84bdb1f8e13a89958ee37ade7bdcd4a15440287d5bc68c1b61bc6c7629b45d79
        env:
          - name: SECRET_RPC
            valueFrom:
              secretKeyRef:
                name: rpc
                key: http://18.220.101.192:26657
          - name: SECRET_RABBITMQ
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: amqp://watcher:kjadsfuipqwhjfd@165.232.40.207:5672
          - name: SECRET_GRAPHQL
            valueFrom:
              secretKeyRef:
                name: graphql
                key: http://165.232.107.244:8081/v1/graphql
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        # - name: secret-volume
          # mountPath: /secrets/
        - name: config-volume
          mountPath: /configs/
      # volumes:
      # - name: secret-volume
        # secret:
          # secretName: mysecret
      - name: config-volume
        configMap:
          name: example-config #name of our configmap object