apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcanna-watcher-deploy
  labels:
    app: bitcanna-watcher-app
  annotations:
spec:
  selector:
    matchLabels:
      app: bitcanna-watcher-app

  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bitcanna-watcher-app
    spec:
      hostAliases:
      - ip: "159.89.250.255"
        hostnames:
        - "api.mapofzones.com"
      containers:

      - name: bitcanna-1
        image: registry.digitalocean.com/mapofzones/cosmos-watcher-bitcanna:b40f2d7b
        env:
          - name: chain_id
            value: "bitcanna-1"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "150Mi"
            cpu: "30m"
          limits:
            memory: "256Mi"
            cpu: "250m"
