apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtick-watcher-deploy
  labels:
    app: microtick-watcher-app
  annotations:
spec:
  selector:
    matchLabels:
      app: microtick-watcher-app

  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: microtick-watcher-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - microtick-watcher-app
            topologyKey: "kubernetes.io/hostname"
      hostAliases:
      - ip: "159.89.250.255"
        hostnames:
        - "api.mapofzones.com"
      containers:

      - name: microtick-1
        image: registry.digitalocean.com/mapofzones/cosmos-watcher-microtick:9279d9f9
        env:
          - name: chain_id
            value: "microtick-1"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: prodsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "150Mi"
            cpu: "30m"
          limits:
            memory: "256Mi"
            cpu: "250m"
