apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  secret.json: |-
    {
      "rpc" : "http://18.220.101.192:26657",
      "rabbitmq" : "amqp://watcher:kjadsfuipqwhjfd@165.232.40.207:5672",
      "graphql" : "http://165.232.107.244:8081/v1/graphql"
    }
#kubectl create secret generic mysecret --from-file .\golang\secrets\secret.json