apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchers-deploy
  labels:
    app: watchers-app
  annotations:
spec:
  selector:
    matchLabels:
      app: watchers-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: watchers-app
    spec:
      containers:
      - name: regen-devnet-2
        image: registry.digitalocean.com/mapofzones/cosmos-watcher-dev:latest
        env:
          - name: rpc
            value: "http://46.101.95.106:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
      - name: aplikigo-1
        image: registry.digitalocean.com/mapofzones/cosmos-watcher-dev:latest
        env:
          - name: rpc
            value: "http://46.101.95.106:26658"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "5m"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
      - name: stargate-4
        image: registry.digitalocean.com/mapofzones/cosmos-watcher:latest
        env:
          - name: rpc
            value: "http://34.123.30.100:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
      - name: cosmoshub-test-stargate-e
        image: registry.digitalocean.com/mapofzones/cosmos-watcher:latest
        env:
          - name: rpc
            value: "http://162.222.177.241:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
      - name: cosmoshub-3
        image: registry.digitalocean.com/mapofzones/cosmos-watcher:latest
        env:
          - name: rpc
            value: "http://13.209.59.177:26657"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
      - name: musselnet-3
        image: registry.digitalocean.com/mapofzones/cosmos-watcher:latest
        env:
          - name: rpc
            value: "http://188.34.187.55:26657/"
          - name: rabbitmq
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: watcher_rabbitmq
          - name: graphql
            valueFrom:
              secretKeyRef:
                name: devsecret
                key: db_graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "30Mi"
            cpu: "5m"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"